
services:
  server:
    build:
      context: ./server
    container_name: code_now_server
    environment:
      - CORS_ORIGIN=${CORS_ORIGIN}

  client:
    build:
      context: ./client
      args:
        - VITE_SOCKET_URL=${VITE_SOCKET_URL}
    container_name: code_now_client
    depends_on:
      - server
