
services:
  server:
    build:
      context: ./server
    container_name: code_now_server
    ports:
      - "4000:4000"
    environment:
      - CORS_ORIGIN=${CORS_ORIGIN}

  client:
    build:
      context: ./client
      args:
        - VITE_SOCKET_URL=${VITE_SOCKET_URL}
    container_name: code_now_client
    depends_on:
      - server

  nginx:
    build:
      context: ./nginx
    container_name: code_now_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - client
      - server

  certbot:
    image: certbot/certbot
    container_name: code_now_certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
