
services:
  server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    container_name: code_now_server

  client:
    build:
      context: ./client
      args:
        - VITE_SOCKET_URL=http://localhost:4000
    ports:
      - "8080:80" # Map host port 8080 to container port 80
    container_name: code_now_client
    depends_on:
      - server
