
services:
  server:
    build:
      context: ./server
      no_cache: true
      pull: true
    container_name: code_now_server
    ports:
      - "4000:4000"
    environment:
      - CORS_ORIGIN=${CORS_ORIGIN}
      - DEFAULT_PYTHON_CODE=${DEFAULT_PYTHON_CODE:-# Start typing Python code...}
      - DEFAULT_JAVASCRIPT_CODE=${DEFAULT_JAVASCRIPT_CODE:-// Start typing JavaScript code...}
      - MAX_EDITORS=${MAX_EDITORS:-2} # Default to 2 if not set

  client:
    build:
      context: ./client
      args:
        - VITE_SOCKET_URL=${VITE_SOCKET_URL}
    container_name: code_now_client
    depends_on:
      - server

  nginx:
    build:
      context: ./nginx
    container_name: code_now_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - client
      - server

  certbot:
    image: certbot/certbot
    container_name: code_now_certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
