name: Deploy to EC2

on:
  push:
    branches:
      - main # 當推送到 main 分支時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 執行器

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # 拉取程式碼

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # 從 GitHub Secrets 獲取私鑰

    - name: Deploy to EC2
      run: |
        set -ex # Exit immediately if a command exits with a non-zero status, and print commands

        echo "--- Starting Deployment on EC2 ---"
        echo "Verifying current user and permissions:"
        echo "Current user: $(whoami)"
        echo "User ID and groups: $(id)"
        echo "Current working directory: $(pwd)"

        # 將環境變數的 export 移到 SSH 會話內部
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -ex # Enable verbose output and exit on error for the remote shell

          export VITE_SOCKET_URL="${{ secrets.VITE_SOCKET_URL }}"
          export CORS_ORIGIN="${{ secrets.CORS_ORIGIN }}"
          export MAX_EDITORS="${{ secrets.MAX_EDITORS }}"
          export EC2_USERNAME="${{ secrets.EC2_USERNAME }}" # 確保 EC2_USERNAME 也被導出

          echo "EC2_USERNAME (inside SSH): $EC2_USERNAME"
          echo "MAX_EDITORS (inside SSH): $MAX_EDITORS"

          echo "Checking / directory permissions..."
          ls -ld /

          echo "Checking /home directory permissions..."
          ls -ld /home

          echo "Checking /home/ubuntu directory permissions..."
          ls -ld /home/ubuntu || true # Allow failure if directory doesn't exist

          echo "Ensuring /home/ubuntu directory exists and has correct ownership..."
          sudo mkdir -p /home/ubuntu # Create /home/ubuntu if it doesn't exist
          sudo chown -R ubuntu:ubuntu /home/ubuntu # Hardcode ubuntu for testing
          echo "/home/ubuntu directory status after ensuring existence and ownership:"
          ls -ld /home/ubuntu

          echo "Ensuring target project directory exists with sudo..."
          sudo mkdir -p /home/ubuntu/code_now
          echo "Attempting to set ownership of project directory..."
          sudo chown -R ubuntu:ubuntu /home/ubuntu/code_now # Hardcode ubuntu for testing

          echo "Verifying project directory status after creation/ownership change..."
          ls -ld /home/ubuntu/code_now

          echo "Attempting to change into project directory..."
          cd /home/ubuntu/code_now
          echo "Successfully changed directory to: $(pwd)"

          echo "--- Basic Directory Setup Complete. ---"
          # 以下是原來的部署邏輯，暫時註釋掉，待解決目錄問題後再恢復
          # git pull origin main # 拉取最新程式碼
          # echo "Latest code pulled."
          
          # docker-compose down --volumes # 停止並移除舊的容器和卷
          # echo "Old containers and volumes removed."

          # docker rmi $(docker images -q --filter "dangling=true") || true
          # docker rmi $(docker images -q --filter "label=com.docker.compose.project=code_now") || true
          # echo "Old Docker images removed."

          # docker-compose up -d --build # 重建並啟動新的容器
          # echo "New containers built and started."

          # docker ps -a
          # docker images

          echo "--- Deployment to EC2 Finished (Partial) ---"
        EOF
