name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} 'bash -s' <<'EOF'
          set -ex
          
          # Navigate to the project directory
          cd /home/ubuntu/code_now
          
          # Pull the latest changes
          git pull origin main
          echo "--- Latest code pulled. ---"

          # Create .env file with secrets for Docker Compose using printf for safety
          echo "--- Creating .env file... ---"
          printf "VITE_SOCKET_URL=%s\nCORS_ORIGIN=%s\nMAX_EDITORS=%s\n" \
            "${{ secrets.VITE_SOCKET_URL }}" \
            "${{ secrets.CORS_ORIGIN }}" \
            "${{ secrets.MAX_EDITORS }}" > .env

          # Stop the running containers
          docker compose down
          echo "--- Old containers stopped. ---"
          
          # Build and start new containers
          docker compose up -d --build
          echo "--- Building and starting new containers... ---"
          
          echo "--- Deployment to EC2 Finished ---"
          docker ps -a
        EOF
